{{- if and .Values.sessions.encryptionKey (not .Values.sessions.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-env" (include "scrub.fullname" .) }}
  labels:
    {{- include "scrub.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption-key: {{ .Values.sessions.encryptionKey | quote }}
{{- end }}
